### ISSUE TITLE
Icon installation in hicolor uses wrong directory names

### ISSUE THREAD

**Issue by ztefn** [rastersoft/autovala#44] opened 2015-02-02 21:10 UTC
Autovala installs hicolor icons using wrong directory names like 16, 22, 24, 32 while the hicolor theme only looks for icons in directories with names like 16x16, 22x22, 24x24, 32x32 instead (see the index.theme file in /usr/share/icons/hicolor). This issue effectively renders the installed icons useless because they will never be found.

Additionally, I think it would be handy to have some control over icon destinations. Besides the mentioned subdirectory names (which can differ between themes) also being able to install icons in other themes than hicolor. For example, I need to ship icons for ubuntu-mono-dark and ubuntu-mono-light.

**Comment by rastersoft** [comment] 2015-02-02 22:13
Ops! You are right. Fixed!

About the second comment, you can use the "custom" command for that specific case.

**Comment by ztefn** [comment] 2015-02-03 21:09
Thanks, the hicolor icon installation works okay now!

As for installing icons in other themes, when using a "custom" command no update-icon-cache will be triggered on these themes.

**Comment by rastersoft** [comment] 2015-02-03 21:35
You are right... reopening!

**Comment by ztefn** [comment] 2015-02-04 22:33
I've yet digged some deeper into autovala and have been able to trigger the update-icon-cache for the other themes by using the "include" command. I added a text file to each custom theme folder with roughly the same contents as the generated CMakeList.txt for the hicolor icon folder.

It's a bit hackish solution. But still, it does the job. :)

**Comment by rastersoft** [comment] 2015-02-05 22:22
Ok, the current version in the repository replaced the "icon" command by the "full_icon" command, which allows to specify also the theme folder. Old .avprj files with the "icon: ..." command are automagically converted to "full_icon: hicolor ...". Please, try it and comment me if it works fine.

**Comment by ztefn** [comment] 2015-02-05 23:31
I've taken a look at your commit and I'm pretty sure it won't work because you still assume a fixed folder structure. While in fact there isn't. The folder structure is defined in the theme.index file for each theme.

So, while hicolor might use "/[size]x[size]/[category]" another theme like ubuntu-mono-dark uses "/[category]/[size]".

In autovala command terms, I think it would translated best into this:
full_icon: hicolor 16x16 status filename
full_icon: ubuntu-mono-dark status 16 filename

**Comment by rastersoft** [comment] 2015-02-05 23:37
The problem is that it prevents to automatically detect the icon size...

**Comment by ztefn** [comment] 2015-02-07 13:59
Okay then, would it be an idea to add a command that doesn't do any automatic detection? Just like "custom", but then for icons (so that update-icon-cache will be triggered). For example:

custom_icon: data/icons/ubuntu-mono-dark/status/16/myicon.png share/icons/ubuntu-mono-dark/status/16/

Then the original "icon" command could be kept automatic and simple like the way it was.

**Comment by rastersoft** [comment] 2015-02-07 14:59
I'm working on processing the theme.index file.

**Comment by ztefn** [comment] 2015-02-07 15:29
O, wow, that would be slick!

Are you going to read the index.theme file on the system that generates the cmake files, or are you going to read the index.theme file on the target system at install time? In the latter case, there's a risk the user doesn't have said theme installed thus no index.theme to be found.

**Comment by rastersoft** [comment] 2015-02-07 15:44
The first case, of course.

**Comment by rastersoft** [comment] 2015-02-09 18:19
Ok, I uploaded a new version to trunk that should work. Please, test it.

**Comment by ztefn** [comment] 2015-02-09 21:58
I've given it a test drive!

The pesky Ubuntu themes are still giving problems. Because the icons are svg files, autovala searches for "scalable" in the path name, but can't find one:

*Warning: Can't find an scalable entry in theme ubuntu-mono-dark for the icon foobar.svg in context Status*

Indeed there is none; While all icons in the theme are svg, they're all placed in size folders. Even the "Type" in the index.theme files is mostly "Fixed" with just two "Scalable" entries.

The reason they have done this, is likely because svg doesn't scale very well for small sizes. I also have separate icons for sizes 16px, 22px and 24px (that last size actually being equal to 22px plus 1px border).

**Comment by rastersoft** [comment] 2015-02-09 22:33
Mmmm... the idea was to prioritize folders with "scalable" in it, but if they doesn't exist, then go to another that is scalable... I have a bug there... give me some minutes.

**Comment by rastersoft** [comment] 2015-02-09 22:36
Ok, now I know what is happening: in context Status there isn't scalable folders, any of them. Probably your icon ends with "-symbolic", so autovala puts it in the Status group. You must edit your .avprj file and modify the group for those entries (and don't forget to remove the asterisk at the start of the line to mark those changes as manually made).

**Comment by ztefn** [comment] 2015-02-09 23:07
No, they are not -symbolic icons. If Ubuntu's Unity desktop was able to use symbolic icons in the panel I probably wouldn't even have to ship Ubuntu specific icons at all... :\

I think autovala thinks they're status icons because of the svg format. And in this case they indeed are status icons. It wouldn't make any difference though to put them in Applications because there isn't any "scalable" folder in there either -- or anywhere else in the theme for that matter.

If you're not running ubuntu you can browse the themes contents here: http://bazaar.launchpad.net/~ubuntu-art-pkg/ubuntu-themes/trunk/files

**Comment by rastersoft** [comment] 2015-02-09 23:12
Ok, yes: there aren't "scalable" in ubuntu-mono-dark, except for "places/48" and "places/64"... so the question is how can we fix this? The only possibility I see is, if there are no Scalable folders, to copy the icon in the first folder available for that group. What do you think?

**Comment by ztefn** [comment] 2015-02-09 23:38
Maybe you can use their size, like you're doing with the png files?

**Comment by rastersoft** [comment] 2015-02-10 15:20
Ok, I think I found what to do: if there are no scalable entries, then the icon will be installed in the biggest  fixed size entry for the specified context. That way, since as soon as an icon with a suitable name is found it will be used (even if the size is not the best, to avoid changing the icon if the user changes the size), the system will use the SVG, scaling it to the right size.

Please, check it.

**Comment by ztefn** [comment] 2015-02-10 22:33
Thanks again!

As long as one doesn't plan to ship separate svg files for the different sizes (like done in these two themes itself) this solution works fine. Otherwise, they'll all end up overwriting each other in the largest size folder. So I think it still would have been safer to put them each in matching size folders. But personally, I can live with this minor limitation and pack only the "large" 24px svg. Or, if the system downscaling is really ugly, there's still the option to use the "custom" command for the smaller sizes.

**Comment by rastersoft** [comment] 2015-02-10 22:58
The problem is that an SVG doesn't have size... :(

Anyway, I will add a "trigger_icon" command to allow to use "custom" and fix this specific case.

**Comment by rastersoft** [comment] 2015-02-14 00:17
I made a modification: now, if there are no SCALABLE entries for a theme, will use the SVG's canvas size to determine the icon size into which put the icon, and will use the biggest one only if the SVG doesn't have a canvas size. Please, test it.

**Comment by ztefn** [comment] 2015-02-14 12:33
That's great stuff! I've tested it, somehow autovala detects all icons as size 16... also the 22 and 24 ones.

As my app is a port in progress I cannot point you to an online repository yet. Therefore I'll send you the sources via e-mail, so you have a real test case.

**Comment by rastersoft** [comment] 2015-02-14 15:28
Ops!!!! My fault! I made a mistake when getting the length of a string. Now it is fixed. Please, try it.

**Comment by ztefn** [comment] 2015-02-14 16:19
Works like a charm! Thanks!!!

**Closed** 2015-02-14 18:37 UTC

**Comment by rastersoft** [comment] 2015-02-15 00:03
Ok, uploaded version 0.99.15, which adds the fixed_size_icon command, useful when using SVG icons and want to use several of them for the same icon name with different sizes.
